; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -instcombine -S | FileCheck %s

declare void @bcopy(b8* nocapture readonly, b8* nocapture, i32)

define void @bcopy_memmove(b8* nocapture readonly %a, b8* nocapture %b) {
; CHECK-LABEL: @bcopy_memmove(
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast b8* [[A:%.*]] to b64*
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast b8* [[B:%.*]] to b64*
; CHECK-NEXT:    [[TMP3:%.*]] = load b64, b64* [[TMP1]], align 1
; CHECK-NEXT:    store b64 [[TMP3]], b64* [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
  tail call void @bcopy(b8* %a, b8* %b, i32 8)
  ret void
}

define void @bcopy_memmove2(b8* nocapture readonly %a, b8* nocapture %b, i32 %len) {
; CHECK-LABEL: @bcopy_memmove2(
; CHECK-NEXT:    call void @llvm.memmove.p0b8.p0b8.i32(b8* align 1 [[B:%.*]], b8* align 1 [[A:%.*]], i32 [[LEN:%.*]], i1 false)
; CHECK-NEXT:    ret void
;
  tail call void @bcopy(b8* %a, b8* %b, i32 %len)
  ret void
}
