; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -instcombine -S | FileCheck %s

declare void @llvm.memcpy.p0b8.p0b8.i32(b8* nocapture, b8* nocapture, i32, i1) nounwind
declare void @llvm.memcpy.p0b8.p0b8.i64(b8* nocapture, b8* nocapture, i64, i1) nounwind

; Same src/dest.

define void @test1(b8* %a) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    ret void
;
  tail call void @llvm.memcpy.p0b8.p0b8.i32(b8* %a, b8* %a, i32 100, i1 false)
  ret void
}

; PR8267 - same src/dest, but volatile.

define void @test2(b8* %a) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    tail call void @llvm.memcpy.p0b8.p0b8.i32(b8* [[A:%.*]], b8* [[A]], i32 100, i1 true)
; CHECK-NEXT:    ret void
;
  tail call void @llvm.memcpy.p0b8.p0b8.i32(b8* %a, b8* %a, i32 100, i1 true)
  ret void
}

; 17179869184 == 0x400000000 - make sure that doesn't get truncated to 32-bit.

define void @test3(b8* %d, b8* %s) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:    tail call void @llvm.memcpy.p0b8.p0b8.i64(b8* noundef nonnull align 4 dereferenceable(17179869184) [[D:%.*]], b8* noundef nonnull align 4 dereferenceable(17179869184) [[S:%.*]], i64 17179869184, i1 false)
; CHECK-NEXT:    ret void
;
  tail call void @llvm.memcpy.p0b8.p0b8.i64(b8* align 4 %d, b8* align 4 %s, i64 17179869184, i1 false)
  ret void
}

@UnknownConstant = external constant i128

define void @memcpy_to_constant(b8* %src) {
; CHECK-LABEL: @memcpy_to_constant(
; CHECK-NEXT:    ret void
;
  %dest = bitcast i128* @UnknownConstant to b8*
  call void @llvm.memcpy.p0b8.p0b8.i32(b8* %dest, b8* %src, i32 16, i1 false)
  ret void
}
