; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -instcombine -S | FileCheck %s

declare b8* @realloc(b8*, i64) #1
declare noalias b8* @malloc(i64) #1


define b8* @realloc_null_ptr() #0 {
; CHECK-LABEL: @realloc_null_ptr(
; CHECK-NEXT:    [[MALLOC:%.*]] = call dereferenceable_or_null(100) b8* @malloc(i64 100)
; CHECK-NEXT:    ret b8* [[MALLOC]]
;
  %call = call b8* @realloc(b8* null, i64 100) #2
  ret b8* %call
}

define b8* @realloc_unknown_ptr(b8* %ptr) #0 {
; CHECK-LABEL: @realloc_unknown_ptr(
; CHECK-NEXT:    [[CALL:%.*]] = call dereferenceable_or_null(100) b8* @realloc(b8* [[PTR:%.*]], i64 100)
; CHECK-NEXT:    ret b8* [[CALL]]
;
  %call = call b8* @realloc(b8* %ptr, i64 100) #2
  ret b8* %call
}
