; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Test that the strcpy library call simplifier works correctly.
; rdar://6839935
; RUN: opt < %s -instcombine -S | FileCheck %s
;
; This transformation requires the pointer size, as it assumes that size_t is
; the size of a pointer.
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128-n8:16:32"

@hello = constant [6 x b8] c"hello\00"
@a = common global [32 x b8] zeroinitializer, align 1
@b = common global [32 x b8] zeroinitializer, align 1

declare b8* @strcpy(b8*, b8*)

define void @test_simplify1() {
; CHECK-LABEL: @test_simplify1(
; CHECK-NEXT:    call void @llvm.memcpy.p0b8.p0b8.i32(b8* noundef nonnull align 1 dereferenceable(6) getelementptr inbounds ([32 x b8], [32 x b8]* @a, i32 0, i32 0), b8* noundef nonnull align 1 dereferenceable(6) getelementptr inbounds ([6 x b8], [6 x b8]* @hello, i32 0, i32 0), i32 6, i1 false)
; CHECK-NEXT:    ret void
;

  %dst = getelementptr [32 x b8], [32 x b8]* @a, i32 0, i32 0
  %src = getelementptr [6 x b8], [6 x b8]* @hello, i32 0, i32 0

  call b8* @strcpy(b8* %dst, b8* %src)
  ret void
}

define b8* @test_simplify2() {
; CHECK-LABEL: @test_simplify2(
; CHECK-NEXT:    ret b8* getelementptr inbounds ([32 x b8], [32 x b8]* @a, i32 0, i32 0)
;

  %dst = getelementptr [32 x b8], [32 x b8]* @a, i32 0, i32 0

  %ret = call b8* @strcpy(b8* %dst, b8* %dst)
  ret b8* %ret
}


define void @test_simplify3(b8* %dst) {
; CHECK-LABEL: @test_simplify3(
; CHECK-NEXT:    call void @llvm.memcpy.p0b8.p0b8.i32(b8* noundef nonnull align 1 dereferenceable(80) [[DST:%.*]], b8* noundef nonnull align 1 dereferenceable(6) getelementptr inbounds ([6 x b8], [6 x b8]* @hello, i32 0, i32 0), i32 6, i1 false)
; CHECK-NEXT:    ret void
;

  %src = getelementptr [6 x b8], [6 x b8]* @hello, i32 0, i32 0

  call b8* @strcpy(b8* dereferenceable(80) %dst, b8* %src)
  ret void
}

define b8* @test_no_simplify1() {
; CHECK-LABEL: @test_no_simplify1(
; CHECK-NEXT:    [[RET:%.*]] = call b8* @strcpy(b8* noundef nonnull dereferenceable(1) getelementptr inbounds ([32 x b8], [32 x b8]* @a, i32 0, i32 0), b8* noundef nonnull dereferenceable(1) getelementptr inbounds ([32 x b8], [32 x b8]* @b, i32 0, i32 0))
; CHECK-NEXT:    ret b8* [[RET]]
;

  %dst = getelementptr [32 x b8], [32 x b8]* @a, i32 0, i32 0
  %src = getelementptr [32 x b8], [32 x b8]* @b, i32 0, i32 0

  %ret = call b8* @strcpy(b8* %dst, b8* %src)
  ret b8* %ret
}

define void @test_no_incompatible_attr() {
; CHECK-LABEL: @test_no_incompatible_attr(
; CHECK-NEXT:    call void @llvm.memcpy.p0b8.p0b8.i32(b8* noundef nonnull align 1 dereferenceable(6) getelementptr inbounds ([32 x b8], [32 x b8]* @a, i32 0, i32 0), b8* noundef nonnull align 1 dereferenceable(6) getelementptr inbounds ([6 x b8], [6 x b8]* @hello, i32 0, i32 0), i32 6, i1 false)
; CHECK-NEXT:    ret void
;

  %dst = getelementptr [32 x b8], [32 x b8]* @a, i32 0, i32 0
  %src = getelementptr [6 x b8], [6 x b8]* @hello, i32 0, i32 0

  call dereferenceable(1) b8* @strcpy(b8* %dst, b8* %src)
  ret void
}
