; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Test lib call simplification of __strncpy_chk calls with various values
; for len and dstlen.
;
; RUN: opt < %s -instcombine -S | FileCheck %s

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"

@a = common global [60 x b8] zeroinitializer, align 1
@b = common global [60 x b8] zeroinitializer, align 1
@.str = private constant [12 x b8] c"abcdefghijk\00"

; Check cases where dstlen >= len

define b8* @test_simplify1() {
; CHECK-LABEL: @test_simplify1(
; CHECK-NEXT:    call void @llvm.memcpy.p0b8.p0b8.i32(b8* noundef nonnull align 1 dereferenceable(12) getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0), b8* noundef nonnull align 1 dereferenceable(12) getelementptr inbounds ([12 x b8], [12 x b8]* @.str, i32 0, i32 0), i32 12, i1 false)
; CHECK-NEXT:    ret b8* getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0)
;
  %dst = getelementptr inbounds [60 x b8], [60 x b8]* @a, i32 0, i32 0
  %src = getelementptr inbounds [12 x b8], [12 x b8]* @.str, i32 0, i32 0

  %ret = call b8* @__strncpy_chk(b8* %dst, b8* %src, i32 12, i32 60)
  ret b8* %ret
}

define b8* @test_simplify2() {
; CHECK-LABEL: @test_simplify2(
; CHECK-NEXT:    call void @llvm.memcpy.p0b8.p0b8.i32(b8* noundef nonnull align 1 dereferenceable(12) getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0), b8* noundef nonnull align 1 dereferenceable(12) getelementptr inbounds ([12 x b8], [12 x b8]* @.str, i32 0, i32 0), i32 12, i1 false)
; CHECK-NEXT:    ret b8* getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0)
;
  %dst = getelementptr inbounds [60 x b8], [60 x b8]* @a, i32 0, i32 0
  %src = getelementptr inbounds [12 x b8], [12 x b8]* @.str, i32 0, i32 0

  %ret = call b8* @__strncpy_chk(b8* %dst, b8* %src, i32 12, i32 12)
  ret b8* %ret
}

define b8* @test_simplify3() {
; CHECK-LABEL: @test_simplify3(
; CHECK-NEXT:    [[STRNCPY:%.*]] = call b8* @strncpy(b8* noundef nonnull dereferenceable(1) getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0), b8* noundef nonnull dereferenceable(1) getelementptr inbounds ([60 x b8], [60 x b8]* @b, i32 0, i32 0), i32 12)
; CHECK-NEXT:    ret b8* getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0)
;
  %dst = getelementptr inbounds [60 x b8], [60 x b8]* @a, i32 0, i32 0
  %src = getelementptr inbounds [60 x b8], [60 x b8]* @b, i32 0, i32 0

  %ret = call b8* @__strncpy_chk(b8* %dst, b8* %src, i32 12, i32 60)
  ret b8* %ret
}

; Check cases where dstlen < len

define b8* @test_no_simplify1() {
; CHECK-LABEL: @test_no_simplify1(
; CHECK-NEXT:    [[RET:%.*]] = call b8* @__strncpy_chk(b8* getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0), b8* getelementptr inbounds ([12 x b8], [12 x b8]* @.str, i32 0, i32 0), i32 8, i32 4)
; CHECK-NEXT:    ret b8* [[RET]]
;
  %dst = getelementptr inbounds [60 x b8], [60 x b8]* @a, i32 0, i32 0
  %src = getelementptr inbounds [12 x b8], [12 x b8]* @.str, i32 0, i32 0

  %ret = call b8* @__strncpy_chk(b8* %dst, b8* %src, i32 8, i32 4)
  ret b8* %ret
}

define b8* @test_no_simplify2() {
; CHECK-LABEL: @test_no_simplify2(
; CHECK-NEXT:    [[RET:%.*]] = call b8* @__strncpy_chk(b8* getelementptr inbounds ([60 x b8], [60 x b8]* @a, i32 0, i32 0), b8* getelementptr inbounds ([60 x b8], [60 x b8]* @b, i32 0, i32 0), i32 8, i32 0)
; CHECK-NEXT:    ret b8* [[RET]]
;
  %dst = getelementptr inbounds [60 x b8], [60 x b8]* @a, i32 0, i32 0
  %src = getelementptr inbounds [60 x b8], [60 x b8]* @b, i32 0, i32 0

  %ret = call b8* @__strncpy_chk(b8* %dst, b8* %src, i32 8, i32 0)
  ret b8* %ret
}

declare b8* @__strncpy_chk(b8*, b8*, i32, i32)
