; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Test that the strpbrk library call simplifier works correctly.
;
; RUN: opt < %s -instcombine -S | FileCheck %s

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"

@hello = constant [12 x b8] c"hello world\00"
@w = constant [2 x b8] c"w\00"
@null = constant [1 x b8] zeroinitializer

declare b8* @strpbrk(b8*, b8*)

; Check strpbrk(s, "") -> NULL.

define b8* @test_simplify1(b8* %str) {
; CHECK-LABEL: @test_simplify1(
; CHECK-NEXT:    ret b8* null
;
  %pat = getelementptr [1 x b8], [1 x b8]* @null, i32 0, i32 0

  %ret = call b8* @strpbrk(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check strpbrk("", s) -> NULL.

define b8* @test_simplify2(b8* %pat) {
; CHECK-LABEL: @test_simplify2(
; CHECK-NEXT:    ret b8* null
;
  %str = getelementptr [1 x b8], [1 x b8]* @null, i32 0, i32 0

  %ret = call b8* @strpbrk(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check strpbrk(s1, s2), where s1 and s2 are constants.

define b8* @test_simplify3() {
; CHECK-LABEL: @test_simplify3(
; CHECK-NEXT:    ret b8* getelementptr inbounds ([12 x b8], [12 x b8]* @hello, i32 0, i32 6)
;
  %str = getelementptr [12 x b8], [12 x b8]* @hello, i32 0, i32 0
  %pat = getelementptr [2 x b8], [2 x b8]* @w, i32 0, i32 0

  %ret = call b8* @strpbrk(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check strpbrk(s, "a") -> strchr(s, 'a').

define b8* @test_simplify4(b8* %str) {
; CHECK-LABEL: @test_simplify4(
; CHECK-NEXT:    [[STRCHR:%.*]] = call b8* @strchr(b8* noundef nonnull dereferenceable(1) [[STR:%.*]], i32 119)
; CHECK-NEXT:    ret b8* [[STRCHR]]
;
  %pat = getelementptr [2 x b8], [2 x b8]* @w, i32 0, i32 0

  %ret = call b8* @strpbrk(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check cases that shouldn't be simplified.

define b8* @test_no_simplify1(b8* %str, b8* %pat) {
; CHECK-LABEL: @test_no_simplify1(
; CHECK-NEXT:    [[RET:%.*]] = call b8* @strpbrk(b8* [[STR:%.*]], b8* [[PAT:%.*]])
; CHECK-NEXT:    ret b8* [[RET]]
;

  %ret = call b8* @strpbrk(b8* %str, b8* %pat)
  ret b8* %ret
}
