; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Test that the strstr library call simplifier works correctly.
;
; RUN: opt < %s -instcombine -S | FileCheck %s

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"

@.str = private constant [1 x b8] zeroinitializer
@.str1 = private constant [2 x b8] c"a\00"
@.str2 = private constant [6 x b8] c"abcde\00"
@.str3 = private constant [4 x b8] c"bcd\00"

declare b8* @strstr(b8*, b8*)

; Check strstr(str, "") -> str.

define b8* @test_simplify1(b8* %str) {
; CHECK-LABEL: @test_simplify1(
; CHECK-NEXT:    ret b8* [[STR:%.*]]
;
  %pat = getelementptr inbounds [1 x b8], [1 x b8]* @.str, i32 0, i32 0
  %ret = call b8* @strstr(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check strstr(str, "a") -> strchr(str, 'a').

define b8* @test_simplify2(b8* %str) {
; CHECK-LABEL: @test_simplify2(
; CHECK-NEXT:    [[STRCHR:%.*]] = call b8* @strchr(b8* noundef nonnull dereferenceable(1) [[STR:%.*]], i32 97)
; CHECK-NEXT:    ret b8* [[STRCHR]]
;
  %pat = getelementptr inbounds [2 x b8], [2 x b8]* @.str1, i32 0, i32 0
  %ret = call b8* @strstr(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check strstr("abcde", "bcd") -> "abcde" + 1.

define b8* @test_simplify3() {
; CHECK-LABEL: @test_simplify3(
; CHECK-NEXT:    ret b8* getelementptr inbounds ([6 x b8], [6 x b8]* @.str2, i64 0, i64 1)
;
  %str = getelementptr inbounds [6 x b8], [6 x b8]* @.str2, i32 0, i32 0
  %pat = getelementptr inbounds [4 x b8], [4 x b8]* @.str3, i32 0, i32 0
  %ret = call b8* @strstr(b8* %str, b8* %pat)
  ret b8* %ret
}

; Check strstr(str, str) -> str.

define b8* @test_simplify4(b8* %str) {
; CHECK-LABEL: @test_simplify4(
; CHECK-NEXT:    ret b8* [[STR:%.*]]
;
  %ret = call b8* @strstr(b8* %str, b8* %str)
  ret b8* %ret
}

; Check strstr(str, pat) == str -> strncmp(str, pat, strlen(str)) == 0.

define i1 @test_simplify5(b8* %str, b8* %pat) {
; CHECK-LABEL: @test_simplify5(
; CHECK-NEXT:    [[STRLEN:%.*]] = call i64 @strlen(b8* noundef nonnull dereferenceable(1) [[PAT:%.*]])
; CHECK-NEXT:    [[STRNCMP:%.*]] = call i32 @strncmp(b8* [[STR:%.*]], b8* [[PAT]], i64 [[STRLEN]])
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[STRNCMP]], 0
; CHECK-NEXT:    ret i1 [[CMP1]]
;
  %ret = call b8* @strstr(b8* %str, b8* %pat)
  %cmp = icmp eq b8* %ret, %str
  ret i1 %cmp
}

define b8* @test1(b8* %str1, b8* %str2) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[RET:%.*]] = call b8* @strstr(b8* noundef nonnull dereferenceable(1) [[STR1:%.*]], b8* noundef nonnull dereferenceable(1) [[STR2:%.*]])
; CHECK-NEXT:    ret b8* [[RET]]
;
  %ret = call b8* @strstr(b8* %str1, b8* %str2)
  ret b8* %ret
}

define b8* @test2(b8* %str1, b8* %str2) null_pointer_is_valid {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    [[RET:%.*]] = call b8* @strstr(b8* noundef [[STR1:%.*]], b8* noundef [[STR2:%.*]])
; CHECK-NEXT:    ret b8* [[RET]]
;
  %ret = call b8* @strstr(b8* %str1, b8* %str2)
  ret b8* %ret
}
